---
title: 'Weather: Loss of Human Life and Property Damage'
output: pdf_document
---

```{r load_libraries, echo=FALSE, message=FALSE} 
library(dplyr)
library(lubridate)
library(tidyr)
library(ggplot2)
```

```{r load_data, echo=FALSE}

# storm.data <- tbl_df(
#   read.csv(file = "data//StormData.csv", header = TRUE, #nrows = 1000,
#            colClasses = c(
#              "NULL", 
#              "character", #date
#              rep("NULL", times = 4),
#              "factor", #state
#              "factor", #type
#              rep("NULL", times = 14),
#              "numeric", #fatal
#              "numeric", #inju
#              "numeric", #property
#              rep("NULL", times = 12)
#           )
#   )
# )
# 
# 
# saveRDS(object = storm.data, ascii = FALSE, compress = "bzip2", file = "data//stormdata.rds")

storm.data <- readRDS(file = "data//stormdata.rds")

```

```{r manip_data, echo=FALSE}
storm.data2 <- storm.data %>% 
  transmute(
    date = lubridate::mdy(
      x = sub(x = BGN_DATE, pattern = "([0-9/]+).*", replacement = "\\1")),
    year = year(date),
    EVTYPE, FATALITIES, INJURIES, PROPDMG
)
```

# Overview

This analysis focuses on extreme weather events from 1993 through 2011,
corresponding with broad categories: tornadoes, hurricanes, floods, and heat.


```` {r shrink_data, echo=FALSE}
impact <- storm.data2 %>%
  filter(year >= 1993) %>%
  group_by(EVTYPE, year) %>%
  summarise(
    fatalities = sum(FATALITIES), 
    property = sum(PROPDMG), 
    count = n()
    ) %>%
  mutate(
    torn = grepl(pattern = "TORN", x = EVTYPE),
    hurr = grepl(pattern = "HURR|TYPH", x = EVTYPE),
    floo = grepl(pattern = "FLOO", x = EVTYPE),
    heat = grepl(pattern = "HEAT", x = EVTYPE)
)

#overlap of categories?
max(impact$torn + impact$hurr + impact$floo + impact$heat)
```

